//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileVerifierLib.UserControls.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FileHashListViewResources {
        
        //private static global::System.Resources.ResourceManager resourceMan;
      private static global::System.ComponentModel.ComponentResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FileHashListViewResources()
        {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        /*[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                  global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FileVerifierLib.UserControls.Properties.FileHashListViewResources", typeof(FileHashListViewResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }*/
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.ComponentModel.ComponentResourceManager ResourceManager
        {
          get
          {
            if (object.ReferenceEquals(resourceMan, null))
            {
              global::System.ComponentModel.ComponentResourceManager temp = new global::System.ComponentModel.ComponentResourceManager(typeof(FileHashListView));
              resourceMan = temp;
            }
            return resourceMan;
          }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string COLUMN_NAME_TEXT {
            get {
                return ResourceManager.GetString("COLUMN_NAME_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checksum.
        /// </summary>
        internal static string COLUMN_HASH_TEXT {
            get {
                return ResourceManager.GetString("COLUMN_HASH_TEXT", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        internal static string COLUMN_RESULT_TEXT
        {
          get
          {
            return ResourceManager.GetString("COLUMN_RESULT_TEXT", resourceCulture);
          }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not processed.
        /// </summary>
        internal static string ERROR_TEXT_FILE_NOT_PROCESSED {
            get {
                return ResourceManager.GetString("ERROR_TEXT_FILE_NOT_PROCESSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found.
        /// </summary>
        internal static string ERROR_TEXT_FILE_NOT_FOUND {
            get {
                return ResourceManager.GetString("ERROR_TEXT_FILE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access denied.
        /// </summary>
        internal static string ERROR_TEXT_FILE_NOT_ACCESSIBLE {
            get {
                return ResourceManager.GetString("ERROR_TEXT_FILE_NOT_ACCESSIBLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checksum not specified.
        /// </summary>
        internal static string ERROR_TEXT_HASH_NOT_SPECIFIED {
            get {
                return ResourceManager.GetString("ERROR_TEXT_HASH_NOT_SPECIFIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checksum not matched.
        /// </summary>
        internal static string ERROR_TEXT_HASH_NOT_MATCHED {
            get {
                return ResourceManager.GetString("ERROR_TEXT_HASH_NOT_MATCHED", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string ERROR_TEXT_SUCCESS
        {
          get
          {
            return ResourceManager.GetString("ERROR_TEXT_SUCCESS", resourceCulture);
          }
        }
    }
}
